---
- hosts: 172.31.18.8
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      state: present
    
  - name: install wget
    apt:
      name: wget
      statee: present
    ignore_errors: yes  

  - name: install tree
    apt:
      name: tree
      state: present
